# Generated by Django 5.1.1 on 2024-09-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
